import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>LOL Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>My League of Legends Profile</h1>

      <footer className={styles.footer}>
        <a
          href="http://portfolio.ruitangcs.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Designed and created by Rui Tang
        </a>
      </footer>
    </div>
  )
}
