import Head from "next/head";
import styles from "../styles/Home.module.css";
import Router from "next/router";
import styled from "styled-components";
import { useState } from "react";

export default function Home() {
  const [searchId, setSearchId] = useState("");

  const search = (e) => {
    e.preventDefault();
    if (searchId.length > 0) {
      Router.push(`/profile/${searchId}`);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>LOL Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>My League of Legends Profile</h1>
      <SearchContainer>
        <SearchForm onSubmit={search}>
          <input
            placeholder="Summoner Id..."
            onChange={(e) => setSearchId(e.target.value)}
          />
        </SearchForm>
      </SearchContainer>

      <footer className={styles.footer}>
        <a
          href="http://portfolio.ruitangcs.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Designed and created by Rui Tang
        </a>
      </footer>
    </div>
  );
}

const SearchContainer = styled.div``;

const SearchForm = styled.form``;
